# Generated by Django 5.0.3 on 2025-01-22 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("team", "0002_plan"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="plan",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teams",
                to="team.plan",
            ),
            preserve_default=False,
        ),
    ]
