# Generated by Django 5.0.3 on 2025-01-26 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userprofile", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="account_tier",
            field=models.CharField(
                choices=[("basic", "Basic"), ("pro", "Pro"), ("premium", "Premium")],
                default="basic",
                max_length=20,
            ),
        ),
    ]
