# Generated by Django 5.0.3 on 2025-01-20 02:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lead", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lead",
            old_name="desrcipton",
            new_name="desrciption",
        ),
    ]
