# Generated by Django 5.0.3 on 2025-01-21 04:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lead", "0003_rename_desrciption_lead_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="converted_to_client",
            field=models.BooleanField(default=False),
        ),
    ]
